[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/rust-cross/manylinux2014-cross:aarch64"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/rust-cross/manylinux2014-cross:x86_64"

[target.x86_64-linux-android]
dockerfile = "./tmp_docker/Dockerfile.x86_64-linux-android"

[target.i686-linux-android]
dockerfile = "./tmp_docker/Dockerfile.i686-linux-android"

[target.aarch64-linux-android]
dockerfile = "./tmp_docker/Dockerfile.aarch64-linux-android"

[target.armv7-linux-androideabi]
dockerfile = "./tmp_docker/Dockerfile.armv7-linux-androideabi"
