[target.aarch64-linux-android]
pre-build = ["dpkg --add-architecture arm64 && apt-get update && apt-get install --assume-yes libzmq3-dev:arm64"]

[target.armv7-linux-androideabi]
dockerfile = "./docker/cross/target.armv7-linux-androideabi.dockerfile"

[target.i686-linux-android]
dockerfile = "./docker/cross/target.i686-linux-android.dockerfile"

[target.x86_64-linux-android]
dockerfile = "./docker/cross/target.x86_64-linux-android.dockerfile"
