name: "Indy-VDR"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish-binaries:
        description: "Publish Binaries to Release (will create a release if no release exits for branch or tag)"
        required: true
        default: false
        type: boolean
      publish-wrappers:
        description: "Publish Wrappers to Registries"
        required: true
        default: false
        type: boolean

jobs:
  build-android:
    name: build android libraries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          [
            aarch64-linux-android,
            armv7-linux-androideabi,
            i686-linux-android,
            x86_64-linux-android,
          ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{matrix.architecture}} --package indy-vdr
      - name: Save library
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.architecture}}
          path: target/${{ matrix.architecture }}/release/libindy_vdr.so
  create_android_library:
    name: Create android libs
    runs-on: ubuntu-latest
    needs: build-android

    steps:
      - name: Fetch libraries
        uses: actions/download-artifact@v3
      - run: |
          sudo mkdir ./libs
          sudo mv aarch64-linux-android   ./libs/arm64-v8a
          sudo mv armv7-linux-androideabi ./libs/armeabi-v7a
          sudo mv i686-linux-android      ./libs/x86
          sudo mv x86_64-linux-android    ./libs/x86_64
      - name: Save Android library
        uses: actions/upload-artifact@v2
        with:
          name: android-jniLibs
          path: ./libs
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            aarch64-linux-android
            armv7-linux-androideabi
            i686-linux-android
            x86_64-linux-android
          failOnError: false
