name: "Indy-VDR"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish packages"
        required: true
        default: "false"

jobs:
  build-android:
    name: Build Android Libraries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - x86_64-linux-android

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Android library
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.architecture }} --release --package indy-vdr
      - name: Save library
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.architecture }}
          path: target/${{ matrix.architecture }}/release/libindy_vdr.so

  create-android-library:
    name: Create Android Library
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Fetch libraries
        uses: actions/download-artifact@v3
      - name: Create Android Library directory
        run: |
          sudo mkdir ./libs
          sudo mv x86_64-linux-android    ./libs/x86_64
      - name: Save Android library
        uses: actions/upload-artifact@v2
        with:
          name: android-libraries
          path: ./libs
      - name: Remove unneeded artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            x86_64-linux-android
          failOnError: false
