name: "Indy-VDR"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish-binaries:
        description: "Publish Binaries to Release (will create a release if no release exits for branch or tag)"
        required: true
        default: false
        type: boolean
      publish-wrappers:
        description: "Publish Wrappers to Registries"
        required: true
        default: false
        type: boolean

jobs:
  build-ios:
    name: build ios xcframework
    runs-on: macos-latest
    strategy:
      matrix:
        architecture:
          [aarch64-apple-ios, aarch64-apple-ios-sim, x86_64-apple-ios]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.architecture}}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{matrix.architecture}} --release --package indy-vdr
      - name: Save static library
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.architecture}}
          path: target/${{ matrix.architecture }}/release/libindy_vdr.a

  create-ios-xcframework:
    name: Create ios xcframework
    runs-on: macos-latest
    needs: build-ios
    steps:
      - uses: actions/checkout@v2
      - name: Fetch static libraries
        uses: actions/download-artifact@v3
      - run: >
          lipo -create aarch64-apple-ios-sim/libindy_vdr.a \
          x86_64-apple-ios/libindy_vdr.a \
          -output libindy_vdr.a
      - run: >
          xcodebuild -create-xcframework \
            -library aarch64-apple-ios/libindy_vdr.a -headers libindy_vdr/include/libindy_vdr.h \
            -library libindy_vdr.a                   -headers libindy_vdr/include/libindy_vdr.h \
            -output indy_vdr.xcframework
      - name: Save xcframework
        uses: actions/upload-artifact@v3
        with:
          name: indy_vdr.xcframework
          path: indy_vdr.xcframework
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            aarch64-apple-ios
            aarch64-apple-ios-sim
            x86_64-apple-ios
          failOnError: false
